# Generated by Django 5.2.7 on 2025-10-27 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_remove_course_lecturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendance_radius',
            field=models.IntegerField(default=100, help_text='Allowed radius for attendance (meters)'),
        ),
        migrations.AddField(
            model_name='course',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for attendance check', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for attendance check', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='ABSENT', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='api.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
