# Generated by Django 5.2.7 on 2025-10-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_attendance_radius_course_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attendance_radius',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location_lon',
        ),
        migrations.AddField(
            model_name='user',
            name='master_pin',
            field=models.CharField(blank=True, help_text='Master PIN for universal attendance (Admin Only)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location_lat', models.DecimalField(decimal_places=6, help_text='Latitude for attendance check', max_digits=9)),
                ('location_lon', models.DecimalField(decimal_places=6, help_text='Longitude for attendance check', max_digits=9)),
                ('attendance_radius', models.IntegerField(default=100, help_text='Allowed radius (meters)')),
                ('attendance_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('pin_generated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='api.course')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time'],
                'unique_together': {('course', 'scheduled_date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendance', to='api.lecture'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture')},
        ),
    ]
