# Generated by Django 5.2.7 on 2025-10-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_attendance_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='timezone',
            field=models.CharField(choices=[('Africa/Cairo', 'Cairo (EET/EEST)'), ('Africa/Khartoum', 'Khartoum (CAT)'), ('UTC', 'UTC')], default='Africa/Cairo', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
