# File: backend/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView
from rest_framework.routers import DefaultRouter
from .views import (
    UserRegistrationView, 
    CustomTokenObtainPairView, 
    UserProfileView,
    UserListView, # <-- NEW IMPORT
    DepartmentViewSet,
    CourseViewSet,
    EnrollmentViewSet
)

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'departments', DepartmentViewSet)
router.register(r'courses', CourseViewSet)
router.register(r'enrollments', EnrollmentViewSet)

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # Auth & Profile Endpoints (manual)
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    
    # NEW: User List Endpoint (manual)
    path('users/', UserListView.as_view(), name='user-list'), 
    
    # ViewSet Endpoints (auto-generated by router)
    path('', include(router.urls)),
]