# File: backend/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView
from rest_framework.routers import DefaultRouter
from .views import (
    UserRegistrationView,
    CustomTokenObtainPairView,
    UserProfileView,
    UserListView,
    DepartmentViewSet,
    CourseViewSet,
    EnrollmentViewSet,
    AttendanceViewSet,
    LectureViewSet # Import the new LectureViewSet
)

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'departments', DepartmentViewSet, basename='department')
router.register(r'courses', CourseViewSet, basename='course')
router.register(r'enrollments', EnrollmentViewSet, basename='enrollment')
router.register(r'attendance', AttendanceViewSet, basename='attendance')
router.register(r'lectures', LectureViewSet, basename='lecture') # Register the LectureViewSet

# The API URLs are now determined automatically by the router for the ViewSets.
urlpatterns = [
    # Auth & Profile Endpoints (manual paths)
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),

    # User List Endpoint (manual path, restricted to Admin in views.py)
    path('users/', UserListView.as_view(), name='user-list'),

    # ViewSet Endpoints (auto-generated by router)
    # This includes paths like:
    # /api/departments/, /api/departments/<id>/
    # /api/courses/, /api/courses/<id>/, /api/courses/<id>/students/
    # /api/enrollments/, /api/enrollments/<id>/, /api/enrollments/my-courses/
    # /api/lectures/, /api/lectures/<id>/, /api/lectures/<id>/generate_pin/
    # /api/attendance/, /api/attendance/<id>/, /api/attendance/mark/, /api/attendance/manual-mark/, /api/attendance/<id>/reports/course/
    path('', include(router.urls)),
]